FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d
COPY ./certs/ssl_certificate.crt /etc/nginx/ssl/
COPY ./certs/ab8fdc503bedbc33.pem /etc/nginx/ssl/ssl_certificate.key

# Copy the built app from the build stage to the nginx web root
COPY build /usr/share/nginx/html

# Expose the desired port
EXPOSE 80
EXPOSE 443

# Start Nginx to serve the app
CMD ["nginx", "-g", "daemon off;"]
